

services:
  # Serviço do Node.js
  app:
    build: .
    container_name: node_app_despesas
    ports:
      - "3000:3000"  # Mapeando a porta 3000 do container para a porta 3000 da máquina
    environment:
      - VITE_API_URL=http://localhost:3001
    networks:
      - despesas-backend_minha_rede

    volumes:
      - .:/app  # Sincronizando o código entre o container e a máquina

networks:
  despesas-backend_minha_rede:
    external: true #usa a rede do backend